### ISSUE TITLE
GETメソッドのContent-Typeがapplication/jsonになっている

### ISSUE THREAD

**Issue by rsogo** [ncdcdev/apppot-sdk-js#9]
@karuru6225 @sat-miyazaki SDKのGateway APIで、GETメソッドを使用した際に、
Content-Typeがapplication/jsonになっています。
Webサービスの呼び出しとしては、GETの場合はContent-Typeが無いの一般的かと思いますが、どうでしょうか？もしくはヘッダーをユーザーが指定できるほうがいいか、ここで検討させてください。

**Comment by rsogo** [comment]
@karuru6225 と会話して、GETの場合はContent-Typeを指定しないようにSDKを修正予定。

**Comment by karuru6225** [comment]
28ae58bd23aa41dd49c37c64a244eff02e771c10
v2.3.33にて対応。
getとdeleteでは、bodyをsendしないようにした。
